### PR TITLE
Jmrunge/issue23

### LINKED ISSUE #23: Drivers initialization should be non blocking
Right now, if MVCP driver fails to load, the other drivers wont get loaded either.  The drivers should be initialized async (non blocking) and a command queue should be implemented for the MVCP server.

### PR DESCRIPTION
**Pull request by jmrunge**
Fixes #23

### CODE REVIEW

File: mosto.js [hunk 1]
```diff
@@ -150,14 +161,13 @@ function mosto(configFile) {
     
     console.log("mbc-mosto: [INFO] Starting mbc-mosto... ") ;
     
-    self.startMvcpServer(function() {
-        self.startWatching();
-        self.initDriver();
-    });
+    self.startMvcpServer();
+    self.startWatching();
```
Comment (xaiki) [inline mosto.js:165]: aren't you missing a .then () here ?

Comment (jmrunge) [inline mosto.js:165]: the "then()" is inside startMvcpServer function.  Shouldnt they be
non-blocking?

2013/4/10 Niv Sardi notifications@github.com

File: mosto.js [hunk 2]
```diff
@@ -64,13 +64,17 @@ function mosto(configFile) {
...
     
     mosto.prototype.playPlaylists = function() {
-        console.log("mbc-mosto: [INFO] Start playing playlists");
-        self.playlists.forEach(function(element, index, array) {
-            if (!element.loaded) {
-                self.appendClip(element.medias);
-                element.loaded = true;
-            }
-        });
+        if (self.server_started) {
```
Comment (xaiki) [inline mosto.js:67]: that feels wrong,
all this should be chained as a promise of the server beeing started, or wait on that promise.

Comment (jmrunge) [inline mosto.js:67]: This function should be erased when @fabriciocosta pushes his branch.  If
you look, the promise code is inside startMvcpServer
There it waits for the promise to call this.  But, this func is called now
from the in-driver, thats why I made this ugly hack.

2013/4/10 Niv Sardi notifications@github.com

File: mosto.js (hunk 1 above)
Comment (Lacrymology) [inline mosto.js:165]: I think these are correct like this. Once the `init`s are run, mosto will just start getting it's callbacks called, right?

Comment (jmrunge) [inline mosto.js:165]: Right.  The thing @xaiki pointed is right to, but I made there an ugly hack
because is a method that will dissapear.  I dont see the point of making
more efforts into this since @fabriciocosta's code is the one that should
implement the command queue in the right way.  I made it non-blocking and
provided a place where the "processQueue" method should be called (now it
just calls "playPlaylists").  I think if I put more code into this, it will
be harder for him to replace this code.

2013/4/10 Tomas Neme notifications@github.com

Comment (xaiki) [inline mosto.js:165]: then let's have @fabriciocosta merge his code asap so we can get rid of this.

Comment (jmrunge) [inline mosto.js:165]: Please!

2013/4/12 Niv Sardi notifications@github.com

Comment (jmrunge) [inline mosto.js:165]: In the meantime, can someone merge this?  Or it will remain unmerged until
@fabriciocosta merges his code...?

2013/4/12 Juan Martin Runge jmrunge@gmail.com

File: test/mosto-init-test.js [hunk 3]
```diff
@@ -0,0 +1,67 @@
+var assert = require("assert"),
+    exec   = require('child_process').exec, 
+    mosto  = require('../mosto');
+
+// SILENCE LOG OUTPUT
+var util = require('util');
+var fs = require('fs');
+var log = fs.createWriteStream('/home/jmrunge/stdout.log');
```
Comment (Lacrymology) [inline test/mosto-init-test.js]: no! why the absolute path?

I'll fix this myself to `./logs/stdout.log`

**Comment by Lacrymology** [comment]
test fails for me. Can be because of wrong melted path in my machine?

```
  start without melted
    #start mosto
      ✓ -- starting mosto shouldnt throw error 
      ✓ -- mvcp server connected should return false 
    #start melted
[Error: mbc-mosto: [ERROR] Error starting MVCP server: Error: connect ECONNREFUSED.
Retrying in 5 seconds...]
VOLVIO
      ✓ -- mvcp server connected should return false 
    #add unit 0 to melted
      1) "before all" hook
  ✖ 1 of 106 tests failed:

  1) start without melted #add unit 0 to melted "before all" hook:
     Error: timeout of 3000ms exceeded
      at null.<anonymous> (/home/lacrymology/workspace/nodejs/inaes/mbc-mosto/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

File: test/mosto-init-test.js (hunk 3 above)
Comment (jmrunge) [inline test/mosto-init-test.js]: will fix it ASAP

File: test/mosto-init-test.js [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+        it('-- mvcp server connected should return false', function() {
+            assert.equal(mosto_server.server_started, false);
+        });
+    });
+    describe('#start melted', function() {
+        before(function(done) {
+            exec("melted", {"timeout": "1000"}, function(error, stdout, stderr) {
+                console.error("VOLVIO");
+                done();
+            });
```
Comment (Lacrymology) [inline test/mosto-init-test.js]: This doesn't realize if melted falis. It fails in my install, and the error appears in L57, because the nc test fails

**Comment by jmrunge** [comment]
Indeed it was because of this...

**Comment by Lacrymology** [comment]
Still, the tests are wrong. Can we talk over them on chat?

File: test/mosto-init-test.js (hunk 4 above)
Comment (jmrunge) [inline test/mosto-init-test.js]: It wasnt ment to test if melted fails.  But we could print an error message to the console.  Makefile should test if melted exists or not, not this test.

**Comment by csrocha** [comment]
@jmrunge : Do you like I make all changes needed to pull this request?

**Comment by jmrunge** [comment]
Please do, im rewriting melted-node to stop hunging up!
Maybe do them on a dependant branch?

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
Fixed all errors/comments.  Please @csrocha, @Lacrymology, @xaiki review it and merge if everything ok?
Thanks!

**Comment by jmrunge** [comment]
Finally maked Travis stop bumping my tests... @csrocha, can you verify nothing is missed and merge?
