### PR TITLE
Jmrunge/fix blank

### LINKED ISSUE #109: Blank.html has hardcoded path
On https://github.com/inaes-tic/mbc-mosto/blob/master/test/videos/blank.xml  you have hardcoded you path.

### PR DESCRIPTION
**Pull request by jmrunge**
Fixes #109 
Requires inaes-tic/mbc-common#14

### CODE REVIEW

File: models/Mosto.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ Mosto.Media = Backbone.Model.extend({
         // end: undefined,
         in: undefined,
         out: undefined,
-        blank: false,
+        blank: false
```
Comment (Lacrymology) [inline models/Mosto.js:38]: I usually leave trailing commas because it's not a syntax error, and it makes it easier to add more fields after that without changing an unrelated line. Is that a problem?

Comment (jmrunge) [inline models/Mosto.js:38]: Not at all.  Thats why I wrote "formatting code" in the commit and not "fixing code".  JS standard (as understood by my IDE) is not to have this trailing commas.  As I will be maintaining this code, I thought it was ok to change it so I stop getting warnings from the IDE.  If it is the same, having or not (despite the unrelated line change), I would prefer to have it this way.  Is this ok with you or should I revert changes?

Comment (xaiki) [inline models/Mosto.js:38]: it only breaks i.e.
i prefer it with trailing comas.

On 27 June 2013 22:53, Juan Martin Runge notifications@github.com wrote:

> In models/Mosto.js:
> 
> > @@ -35,7 +35,7 @@ Mosto.Media = Backbone.Model.extend({
> >          // end: undefined,
> >          in: undefined,
> >          out: undefined,
> > -        blank: false,
> > -        blank: false
> 
> Not at all. Thats why I wrote "formatting code" in the commit and not
> "fixing code". JS standard (as understood by my IDE) is not to have this
> trailing commas. As I will be maintaining this code, I thought it was ok to
> change it so I stop getting warnings from the IDE. If it is the same,
> having or not (despite the unrelated line change), I would prefer to have
> it this way. Is this ok with you or should I revert changes?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/pull/111/files#r4931284
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
Well, renamed blank clip id.  Not changed formatting.  Is this OK for merge?
