### PR TITLE
Jmrunge/clip names

### LINKED ISSUE #12: Melted clip names
Mosto is generating xml to load clips into Melted.  This xml have the name of the clip as file name.  They should be named some way they refer to the playlist id and the clip id for Caspa's driver and the playlist name and the clip name for the Json driver to be able to map them in case Mosto's persisted mapping fails for some reason.

### PR DESCRIPTION
**Pull request by jmrunge**
Fixes #12

### CODE REVIEW

File: api/Playlist.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
-function Playlist(name, startDate, medias, endDate) {
+function Playlist(id, name, startDate, medias, endDate) {
+    this.id        = id;
     this.name      = name;
```
Comment (Lacrymology) [inline api/Playlist.js:3]: shouldn't we lose the `name` variable as well?

File: api/Media.js [hunk 2]
```diff
@@ -1,11 +1,16 @@
-function Media(type, file, length, fps) {
-    this.type   = type;
-    this.file   = file;
-    this.length = length;
-    this.fps    = fps;
+function Media(id, orig_order, actual_order, playlist_id, name, type, file, length, fps) {
+    this.id           = id;
+    this.orig_order   = orig_order;
+    this.actual_order = actual_order;
+    this.playlist_id  = playlist_id;
```
Comment (Lacrymology) [inline api/Media.js:5]: couldn't we save a reference to the playlist, instead of the ID? It'd require some juggling on the drivers, but it's not impossible

File: api/Playlist.js (hunk 1 above)
Comment (Lacrymology) [inline api/Playlist.js:3]: unless you want to keep the name as well, which could be the show name, but I'm not sure I see the point

File: api/Media.js (hunk 2 above)
Comment (jmrunge) [inline api/Media.js:5]: Sure we can, but we will holding instances of playlists in memory just for knowing the id (and the only thing I need of the playlist for this is the id).

File: api/Playlist.js (hunk 1 above)
Comment (jmrunge) [inline api/Playlist.js:3]: I use the name mainly for logging.  I think is more usefull than the id for that.  I dont know if there is a name for playlists in Caspa.  If not, we could lose it.

**Comment by Lacrymology** [comment]
@csrocha please review and merge this

**Comment by Lacrymology** [comment]
Travis says in this last commit tests fail, but I see them pass, and it's just whitespace changes. I think travis is not 100% dependable

**Comment by csrocha** [comment]
Let me check it.

**Comment by Lacrymology** [comment]
they were timeout fails, maybe there was some problem with mongodb?

**Comment by csrocha** [comment]
Ok. No troubles I have found with this PR in the test. I will check what happens with Travis.

Question: Why did you rewrite tests which working well? You must copy the test file and modify the new one to test this fix. Something intelligent is assign the issue id to the name file: "issue#12.js".

**Comment by jmrunge** [comment]
Is this question to me or to @lacrymology?

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by csrocha** [comment]
@jmrunge : This question is generic.

@jmrunge , @Lacrymology , @xaiki : Timeouts happen only in nodejs v0.8, but not in v0.10. Or solve trouble for v0.8 or remove v0.8 from test instances in Travis.

**Comment by Lacrymology** [comment]
I changed the tests because new info was added to the models, and I wasn't testing if this info was being copied correctly! when functionality changes, tests must reflect it

**Comment by jmrunge** [comment]
@csrocha Is this branch ok for merge or should I fix something? I cant see it in the comments...

**Comment by jmrunge** [comment]
@csrocha Is there any reason why this branch isnt merged?
